# Generated by Django 3.2.14 on 2022-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_phonenumber_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persontitle',
            unique_together={('entity', 'title')},
        ),
    ]
