# Generated by Django 3.2.14 on 2022-08-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_persontitle_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='owner_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='owner_entity',
            new_name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('entity', 'first_name', 'last_name', 'sub_name')},
        ),
    ]
